CREATURES_DATA = [
    {
        "id": 1,
        "name": "タナゴ",
        "category": "魚",
        "price": 900,
        "season": "1,2,3,11,12月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 2,
        "name": "オイカワ",
        "category": "魚",
        "price": 200,
        "season": "通年",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 3,
        "name": "フナ",
        "category": "魚",
        "price": 160,
        "season": "通年",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 4,
        "name": "ウグイ",
        "category": "魚",
        "price": 240,
        "season": "通年",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 5,
        "name": "コイ",
        "category": "魚",
        "price": 300,
        "season": "通年",
        "time": "終日",
        "place": "池",
    },
    {
        "id": 6,
        "name": "ニシキゴイ",
        "category": "魚",
        "price": 4000,
        "season": "通年",
        "time": "0時~9時,16時~24時",
        "place": "池",
    },
    {
        "id": 7,
        "name": "キンギョ",
        "category": "魚",
        "price": 1300,
        "season": "通年",
        "time": "終日",
        "place": "池",
    },
    {
        "id": 8,
        "name": "デメキン",
        "category": "魚",
        "price": 1300,
        "season": "通年",
        "time": "9時~16時",
        "place": "池",
    },
    {
        "id": 9,
        "name": "ランチュウ",
        "category": "魚",
        "price": 4500,
        "season": "通年",
        "time": "9時~16時",
        "place": "池",
    },
    {
        "id": 10,
        "name": "メダカ",
        "category": "魚",
        "price": 300,
        "season": "4,5,6,7,8月",
        "time": "終日",
        "place": "池",
    },
    {
        "id": 11,
        "name": "ザリガニ",
        "category": "魚",
        "price": 200,
        "season": "4,5,6,7,8,9月",
        "time": "終日",
        "place": "池",
    },
    {
        "id": 12,
        "name": "スッポン",
        "category": "魚",
        "price": 3750,
        "season": "8,9月",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 13,
        "name": "カミツキガメ",
        "category": "魚",
        "price": 5000,
        "season": "4,5,6,7,8,9,10月",
        "time": "0時~4時,21時~24時",
        "place": "川",
    },
    {
        "id": 14,
        "name": "オタマジャクシ",
        "category": "魚",
        "price": 100,
        "season": "3,4,5,6,7月",
        "time": "終日",
        "place": "池",
    },
    {
        "id": 15,
        "name": "カエル",
        "category": "魚",
        "price": 120,
        "season": "5,6,7,8月",
        "time": "終日",
        "place": "池",
    },
    {
        "id": 16,
        "name": "ドンコ",
        "category": "魚",
        "price": 400,
        "season": "通年",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 17,
        "name": "ドジョウ",
        "category": "魚",
        "price": 400,
        "season": "3,4,5月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 18,
        "name": "ナマズ",
        "category": "魚",
        "price": 800,
        "season": "5,6,7,8,9,10月",
        "time": "0時~9時,16時~24時",
        "place": "池",
    },
    {
        "id": 19,
        "name": "ライギョ",
        "category": "魚",
        "price": 5500,
        "season": "6,7,8月",
        "time": "9時~16時",
        "place": "池",
    },
    {
        "id": 20,
        "name": "ブルーギル",
        "category": "魚",
        "price": 180,
        "season": "通年",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 21,
        "name": "イエローパーチ",
        "category": "魚",
        "price": 300,
        "season": "1,2,3,10,11,12月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 22,
        "name": "ブラックバス",
        "category": "魚",
        "price": 400,
        "season": "通年",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 23,
        "name": "ティラピア",
        "category": "魚",
        "price": 800,
        "season": "6,7,8,9,10月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 24,
        "name": "パイク",
        "category": "魚",
        "price": 1800,
        "season": "9,10,11,12月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 25,
        "name": "ワカサギ",
        "category": "魚",
        "price": 400,
        "season": "1,2,12月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 26,
        "name": "アユ",
        "category": "魚",
        "price": 900,
        "season": "7,8,9月",
        "time": "終日",
        "place": "川",
    },
    {
        "id": 27,
        "name": "ヤマメ",
        "category": "魚",
        "price": 1000,
        "season": "3,4,5,6,9,10,11月",
        "time": "月によって変動",
        "place": "崖の上",
    },
    {
        "id": 28,
        "name": "オオイワナ",
        "category": "魚",
        "price": 3800,
        "season": "3,4,5,6,9,10,11月",
        "time": "0時~9時,16時~24時",
        "place": "崖の上",
    },
    {
        "id": 29,
        "name": "ゴールデントラウト",
        "category": "魚",
        "price": 15000,
        "season": "3,4,5,9,10,11月",
        "time": "0時~9時,16時~24時",
        "place": "崖の上",
    },
    {
        "id": 30,
        "name": "イトウ",
        "category": "魚",
        "price": 15000,
        "season": "1,2,3,12月",
        "time": "0時~9時,16時~24時",
        "place": "崖の上",
    },
    {
        "id": 31,
        "name": "サケ",
        "category": "魚",
        "price": 700,
        "season": "9月",
        "time": "終日",
        "place": "河口",
    },
    {
        "id": 32,
        "name": "キングサーモン",
        "category": "魚",
        "price": 1800,
        "season": "9月",
        "time": "終日",
        "place": "河口",
    },
    {
        "id": 33,
        "name": "シャンハイガニ",
        "category": "魚",
        "price": 2000,
        "season": "9,10,11月",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 34,
        "name": "グッピー",
        "category": "魚",
        "price": 1300,
        "season": "4,5,6,7,8,9,10,11月",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 35,
        "name": "ドクターフィッシュ",
        "category": "魚",
        "price": 1500,
        "season": "5,6,7,8,9月",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 36,
        "name": "エンゼルフィッシュ",
        "category": "魚",
        "price": 3000,
        "season": "5,6,7,8,9,10月",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 37,
        "name": "ベタ",
        "category": "魚",
        "price": 2500,
        "season": "5,6,7,8,9,10月",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 38,
        "name": "ネオンテトラ",
        "category": "魚",
        "price": 500,
        "season": "4,5,6,7,8,9,10,11月",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 39,
        "name": "レインボーフィッシュ",
        "category": "魚",
        "price": 800,
        "season": "5,6,7,8,9,10月",
        "time": "9時~16時",
        "place": "川",
    },
    {
        "id": 40,
        "name": "ピラニア",
        "category": "魚",
        "price": 2500,
        "season": "6,7,8,9月",
        "time": "0時~4時,9時~16時,21時~24時",
        "place": "川",
    },
    {
        "id": 41,
        "name": "アロワナ",
        "category": "魚",
        "price": 10000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 42,
        "name": "ドラド",
        "category": "魚",
        "price": 15000,
        "season": "6,7,8,9月",
        "time": "4時~21時",
        "place": "川",
    },
    {
        "id": 43,
        "name": "ガー",
        "category": "魚",
        "price": 6000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "池",
    },
    {
        "id": 44,
        "name": "ピラルク",
        "category": "魚",
        "price": 10000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "川",
    },
    {
        "id": 45,
        "name": "エンドリケリー",
        "category": "魚",
        "price": 4000,
        "season": "6,7,8,9月",
        "time": "0時~4時,21時~24時",
        "place": "川",
    },
    {
        "id": 46,
        "name": "チョウザメ",
        "category": "魚",
        "price": 10000,
        "season": "1,2,3,9,10,11,12月",
        "time": "終日",
        "place": "河口",
    },
    {
        "id": 47,
        "name": "クリオネ",
        "category": "魚",
        "price": 1000,
        "season": "1,2,3,12月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 48,
        "name": "タツノオトシゴ",
        "category": "魚",
        "price": 1100,
        "season": "4,5,6,7,8,9,10,11月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 49,
        "name": "クマノミ",
        "category": "魚",
        "price": 650,
        "season": "4,5,6,7,8,9月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 50,
        "name": "ナンヨウハギ",
        "category": "魚",
        "price": 1000,
        "season": "4,5,6,7,8,9月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 51,
        "name": "チョウチョウウオ",
        "category": "魚",
        "price": 1000,
        "season": "4,5,6,7,8,9月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 52,
        "name": "ナポレオンフィッシュ",
        "category": "魚",
        "price": 10000,
        "season": "7,8月",
        "time": "4時~21時",
        "place": "海",
    },
    {
        "id": 53,
        "name": "ミノカサゴ",
        "category": "魚",
        "price": 500,
        "season": "4,5,6,7,8,9,10,11月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 54,
        "name": "フグ",
        "category": "魚",
        "price": 5000,
        "season": "1,2,11,12月",
        "time": "0時~4時,21時~24時",
        "place": "海",
    },
    {
        "id": 55,
        "name": "ハリセンボン",
        "category": "魚",
        "price": 250,
        "season": "7,8,9月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 56,
        "name": "アンチョビ",
        "category": "魚",
        "price": 200,
        "season": "通年",
        "time": "4時~21時",
        "place": "海",
    },
    {
        "id": 57,
        "name": "アジ",
        "category": "魚",
        "price": 150,
        "season": "通年",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 58,
        "name": "イシダイ",
        "category": "魚",
        "price": 5000,
        "season": "3,4,5,6,7,8,9,10,11月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 59,
        "name": "スズキ",
        "category": "魚",
        "price": 400,
        "season": "通年",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 60,
        "name": "タイ",
        "category": "魚",
        "price": 3000,
        "season": "通年",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 61,
        "name": "カレイ",
        "category": "魚",
        "price": 300,
        "season": "1,2,3,4,10,11,12月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 62,
        "name": "ヒラメ",
        "category": "魚",
        "price": 800,
        "season": "通年",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 63,
        "name": "イカ",
        "category": "魚",
        "price": 500,
        "season": "1,2,3,4,5,6,7,8,12月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 64,
        "name": "ウツボ",
        "category": "魚",
        "price": 2000,
        "season": "8,9,10月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 65,
        "name": "ハナヒゲウツボ",
        "category": "魚",
        "price": 600,
        "season": "6,7,8,9,10月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 66,
        "name": "マグロ",
        "category": "魚",
        "price": 7000,
        "season": "1,2,3,4,11,12月",
        "time": "終日",
        "place": "桟橋",
    },
    {
        "id": 67,
        "name": "カジキ",
        "category": "魚",
        "price": 10000,
        "season": "1,2,3,4,7,8,9,11,12月",
        "time": "終日",
        "place": "桟橋",
    },
    {
        "id": 68,
        "name": "ロウニンアジ",
        "category": "魚",
        "price": 4500,
        "season": "5,6,7,8,9,10月",
        "time": "終日",
        "place": "桟橋",
    },
    {
        "id": 69,
        "name": "シイラ",
        "category": "魚",
        "price": 6000,
        "season": "5,6,7,8,9,10月",
        "time": "終日",
        "place": "桟橋",
    },
    {
        "id": 70,
        "name": "マンボウ",
        "category": "魚",
        "price": 4000,
        "season": "7,8,9月",
        "time": "4時~21時",
        "place": "海",
    },
    {
        "id": 71,
        "name": "エイ",
        "category": "魚",
        "price": 3000,
        "season": "8,9,10,11月",
        "time": "4時~21時",
        "place": "海",
    },
    {
        "id": 72,
        "name": "ノコギリザメ",
        "category": "魚",
        "price": 12000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "海",
    },
    {
        "id": 73,
        "name": "シュモクザメ",
        "category": "魚",
        "price": 8000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "海",
    },
    {
        "id": 74,
        "name": "サメ",
        "category": "魚",
        "price": 15000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "海",
    },
    {
        "id": 75,
        "name": "ジンベエザメ",
        "category": "魚",
        "price": 13000,
        "season": "6,7,8,9月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 76,
        "name": "コバンザメ",
        "category": "魚",
        "price": 1500,
        "season": "6,7,8,9月",
        "time": "終日",
    },
    {
        "id": 77,
        "name": "チョウチンアンコウ",
        "category": "魚",
        "price": 2500,
        "season": "1,2,3,11,12月",
        "time": "0時~9時,16時~24時",
        "place": "海",
    },
    {
        "id": 78,
        "name": "リュウグウノツカイ",
        "category": "魚",
        "price": 9000,
        "season": "1,2,3,4,5,12月",
        "time": "終日",
        "place": "海",
    },
    {
        "id": 79,
        "name": "デメニギス",
        "category": "魚",
        "price": 15000,
        "season": "通年",
        "time": "0時~4時,21時~24時",
        "place": "海",
    },
    {
        "id": 80,
        "name": "シーラカンス",
        "category": "魚",
        "price": 15000,
        "season": "2,3,4,5,6,7,8,9,10,11月",
        "time": "終日",
        "place": "海（雨の日）",
    },
    {
        "id": 81,
        "name": "ワカメ",
        "category": "海の幸",
        "price": 600,
        "season": "1,2,3,4,5,6,7,10,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 82,
        "name": "ウミブドウ",
        "category": "海の幸",
        "price": 900,
        "season": "6,7,8,9月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 83,
        "name": "ナマコ",
        "category": "海の幸",
        "price": 500,
        "season": "1,2,3,4,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 84,
        "name": "センジュナマコ",
        "category": "海の幸",
        "price": 10000,
        "season": "1,2,11,12月",
        "time": "0時~9時,16時~24時",
        "place": "岩場",
    },
    {
        "id": 85,
        "name": "ヒトデ",
        "category": "海の幸",
        "price": 500,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 86,
        "name": "ウニ",
        "category": "海の幸",
        "price": 1700,
        "season": "5,6,7,8,9月",
        "time": "終日",
        "place": "岩場",
    },
    {
        "id": 87,
        "name": "パイプウニ",
        "category": "海の幸",
        "price": 2000,
        "season": "5,6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 88,
        "name": "イソギンチャク",
        "category": "海の幸",
        "price": 500,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 89,
        "name": "ミズクラゲ",
        "category": "海の幸",
        "price": 600,
        "season": "7,8,9月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 90,
        "name": "ウミウシ",
        "category": "海の幸",
        "price": 600,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 91,
        "name": "アコヤガイ",
        "category": "海の幸",
        "price": 2800,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 92,
        "name": "ムールガイ",
        "category": "海の幸",
        "price": 1500,
        "season": "6,7,8,9,10,11,12月",
        "time": "終日",
        "place": "岩場",
    },
    {
        "id": 93,
        "name": "オイスター",
        "category": "海の幸",
        "price": 1100,
        "season": "1,2,9,10,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 94,
        "name": "ホタテ",
        "category": "海の幸",
        "price": 1200,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 95,
        "name": "バイガイ",
        "category": "海の幸",
        "price": 1000,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 96,
        "name": "サザエ",
        "category": "海の幸",
        "price": 1000,
        "season": "3,4,5,9,10,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 97,
        "name": "アワビ",
        "category": "海の幸",
        "price": 2000,
        "season": "1,6,7,8,9,10,11,12月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 98,
        "name": "オオシャコガイ",
        "category": "海の幸",
        "price": 15000,
        "season": "5,6,7,8,9月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 99,
        "name": "オウムガイ",
        "category": "海の幸",
        "price": 1800,
        "season": "3,4,5,6,9,10,11月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 100,
        "name": "タコ",
        "category": "海の幸",
        "price": 1200,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 101,
        "name": "メンダコ",
        "category": "海の幸",
        "price": 6000,
        "season": "3,4,5,9,10,11月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 102,
        "name": "コウモリダコ",
        "category": "海の幸",
        "price": 10000,
        "season": "5,6,7,8月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 103,
        "name": "ホタルイカ",
        "category": "海の幸",
        "price": 1400,
        "season": "3,4,5,6月",
        "time": "0時~4時,21時~24時",
        "place": "海中",
    },
    {
        "id": 104,
        "name": "ガザミ",
        "category": "海の幸",
        "price": 2200,
        "season": "6,7,8,9,10,11月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 105,
        "name": "ダンジネスクラブ",
        "category": "海の幸",
        "price": 1900,
        "season": "1,2,3,4,5,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 106,
        "name": "ズワイガニ",
        "category": "海の幸",
        "price": 6000,
        "season": "1,2,3,4,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 107,
        "name": "タラバガニ",
        "category": "海の幸",
        "price": 8000,
        "season": "1,2,3,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 108,
        "name": "フジツボ",
        "category": "海の幸",
        "price": 600,
        "season": "通年",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 109,
        "name": "タカアシガニ",
        "category": "海の幸",
        "price": 12000,
        "season": "3,4月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 110,
        "name": "クルマエビ",
        "category": "海の幸",
        "price": 3000,
        "season": "6,7,8,9月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 111,
        "name": "アマエビ",
        "category": "海の幸",
        "price": 1400,
        "season": "1,2,9,10,11,12月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 112,
        "name": "シャコ",
        "category": "海の幸",
        "price": 2500,
        "season": "通年",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 113,
        "name": "イセエビ",
        "category": "海の幸",
        "price": 5000,
        "season": "10,11,12月",
        "time": "0時~4時,21時~24時",
        "place": "海中",
    },
    {
        "id": 114,
        "name": "ロブスター",
        "category": "海の幸",
        "price": 4500,
        "season": "1,4,5,6,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 115,
        "name": "ダイオウグソクムシ",
        "category": "海の幸",
        "price": 12000,
        "season": "7,8,9,10月",
        "time": "0時~4時,9時~16時,21時~24時",
        "place": "海中",
    },
    {
        "id": 116,
        "name": "カブトガニ",
        "category": "海の幸",
        "price": 2500,
        "season": "7,8,9月",
        "time": "0時~4時,21時~24時",
        "place": "海中",
    },
    {
        "id": 117,
        "name": "ホヤ",
        "category": "海の幸",
        "price": 1500,
        "season": "4,5,6,7,8月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 118,
        "name": "チンアナゴ",
        "category": "海の幸",
        "price": 1100,
        "season": "5,6,7,8,9,10月",
        "time": "4時~21時",
        "place": "海中",
    },
    {
        "id": 119,
        "name": "ヒラムシ",
        "category": "海の幸",
        "price": 700,
        "season": "8,9月",
        "time": "0時~9時,16時~24時",
        "place": "海中",
    },
    {
        "id": 120,
        "name": "カイロウドウケツ",
        "category": "海の幸",
        "price": 5000,
        "season": "1,2,10,11,12月",
        "time": "終日",
        "place": "海中",
    },
    {
        "id": 121,
        "name": "モンシロチョウ",
        "category": "虫",
        "price": 160,
        "season": "1,2,3,4,5,6,9,10,11,12月",
        "time": "4時~19時",
        "place": "花/空中",
    },
    {
        "id": 122,
        "name": "モンキチョウ",
        "category": "虫",
        "price": 160,
        "season": "3,4,5,6,9,10月",
        "time": "4時~19時",
        "place": "花/空中",
    },
    {
        "id": 123,
        "name": "アゲハチョウ",
        "category": "虫",
        "price": 240,
        "season": "3,4,5,6,7,8,9月",
        "time": "4時~19時",
        "place": "花/空中",
    },
    {
        "id": 124,
        "name": "カラスアゲハ",
        "category": "虫",
        "price": 2500,
        "season": "3,4,5,6月",
        "time": "4時~19時",
        "place": "花/空中（黒・紫・青の花）",
    },
    {
        "id": 125,
        "name": "アオスジアゲハ",
        "category": "虫",
        "price": 300,
        "season": "4,5,6,7,8月",
        "time": "4時~19時",
        "place": "花/空中",
    },
    {
        "id": 126,
        "name": "オオゴマダラ",
        "category": "虫",
        "price": 1000,
        "season": "通年",
        "time": "8時~19時",
        "place": "花/空中",
    },
    {
        "id": 127,
        "name": "オオムラサキ",
        "category": "虫",
        "price": 3000,
        "season": "5,6,7,8月",
        "time": "4時~19時",
        "place": "花/空中",
    },
    {
        "id": 128,
        "name": "オオカバマダラ",
        "category": "虫",
        "price": 140,
        "season": "9,10,11月",
        "time": "4時~17時",
        "place": "花/空中",
    },
    {
        "id": 129,
        "name": "モルフォチョウ",
        "category": "虫",
        "price": 4000,
        "season": "1,2,3,6,7,8,9,12月",
        "time": "0時~8時,17時~24時",
        "place": "花/空中",
    },
    {
        "id": 130,
        "name": "ミイロタテハ",
        "category": "虫",
        "price": 3000,
        "season": "4,5,6,7,8,9月",
        "time": "8時~17時",
        "place": "花/空中",
    },
    {
        "id": 131,
        "name": "アカエリトリバネアゲハ",
        "category": "虫",
        "price": 2500,
        "season": "1,2,4,5,6,7,8,9,12月",
        "time": "8時~17時",
        "place": "花/空中",
    },
    {
        "id": 132,
        "name": "アレキサンドラトリバネアゲハ",
        "category": "虫",
        "price": 4000,
        "season": "5,6,7,8,9月",
        "time": "8時~16時",
        "place": "花/空中",
    },
    {
        "id": 133,
        "name": "ガ",
        "category": "虫",
        "price": 130,
        "season": "通年",
        "time": "0時~4時,19時~24時",
        "place": "灯りの近く",
    },
    {
        "id": 134,
        "name": "ヨナグニサン",
        "category": "虫",
        "price": 3000,
        "season": "4,5,6,7,8,9月",
        "time": "0時~4時,19時~24時",
        "place": "木/ヤシの木",
    },
    {
        "id": 135,
        "name": "ニシキオオツバメガ",
        "category": "虫",
        "price": 2500,
        "season": "4,5,6,7,8,9月",
        "time": "8時~16時",
        "place": "空中",
    },
    {
        "id": 136,
        "name": "ショウリョウバッタ",
        "category": "虫",
        "price": 200,
        "season": "4,5,6,7,8,9,10,11月",
        "time": "8時~19時",
        "place": "地上",
    },
    {
        "id": 137,
        "name": "トノサマバッタ",
        "category": "虫",
        "price": 600,
        "season": "8,9,10,11月",
        "time": "8時~19時",
        "place": "地上",
    },
    {
        "id": 138,
        "name": "イナゴ",
        "category": "虫",
        "price": 400,
        "season": "8,9,10,11月",
        "time": "8時~19時",
        "place": "地上",
    },
    {
        "id": 139,
        "name": "キリギリス",
        "category": "虫",
        "price": 160,
        "season": "7,8,9月",
        "time": "8時~17時",
        "place": "地上",
    },
    {
        "id": 140,
        "name": "コオロギ",
        "category": "虫",
        "price": 130,
        "season": "9,10,11月",
        "time": "0時~8時,17時~24時",
        "place": "地上",
    },
    {
        "id": 141,
        "name": "スズムシ",
        "category": "虫",
        "price": 430,
        "season": "9,10月",
        "time": "0時~8時,17時~24時",
        "place": "地上",
    },
    {
        "id": 142,
        "name": "カマキリ",
        "category": "虫",
    "price": 430,
        "season": "3,4,5,6,7,8,9,10,11月",
        "time": "8時~17時",
        "place": "花の上",
    },
    {
        "id": 143,
        "name": "ハナカマキリ",
        "category": "虫",
        "price": 2400,
        "season": "3,4,5,6,7,8,9,10,11月",
        "time": "8時~17時",
        "place": "花の上（白い花）",
    },
    {
        "id": 144,
        "name": "ミツバチ",
        "category": "虫",
        "price": 200,
        "season": "3,4,5,6,7月",
        "time": "8時~17時",
        "place": "花の近く",
    },
    {
        "id": 145,
        "name": "ハチ",
        "category": "虫",
        "price": 2500,
        "season": "通年",
        "time": "終日",
        "place": "木（揺すると出現）",
    },
    {
        "id": 146,
        "name": "アブラゼミ",
        "category": "虫",
        "price": 250,
        "season": "7,8月",
        "time": "8時~17時",
        "place": "木",
    },
    {
        "id": 147,
        "name": "ミンミンゼミ",
        "category": "虫",
        "price": 300,
        "season": "7,8月",
        "time": "8時~17時",
        "place": "木",
    },
    {
        "id": 148,
        "name": "クマゼミ",
        "category": "虫",
        "price": 500,
        "season": "7,8月",
        "time": "8時~17時",
        "place": "木",
    },
    {
        "id": 149,
        "name": "ツクツクホウシ",
        "category": "虫",
        "price": 400,
        "season": "8,9月",
        "time": "8時~17時",
        "place": "木",
    },
    {
        "id": 150,
        "name": "ヒグラシ",
        "category": "虫",
        "price": 550,
        "season": "7,8月",
        "time": "4時~8時,16時~19時",
        "place": "木",
    },
    {
        "id": 151,
        "name": "セミのぬけがら",
        "category": "虫",
        "price": 10,
        "season": "7,8月",
        "time": "終日",
        "place": "木",
    },
    {
        "id": 152,
        "name": "アキアカネ",
        "category": "虫",
        "price": 180,
        "season": "9,10月",
        "time": "8時~19時",
        "place": "空中",
    },
    {
        "id": 153,
        "name": "ギンヤンマ",
        "category": "虫",
        "price": 230,
        "season": "4,5,6,7,8,9,10月",
        "time": "8時~17時",
        "place": "空中",
    },
    {
        "id": 154,
        "name": "オニヤンマ",
        "category": "虫",
        "price": 4500,
        "season": "5,6,7,8,9,10月",
        "time": "8時~17時",
        "place": "空中",
    },
    {
        "id": 155,
        "name": "イトトンボ",
        "category": "虫",
        "price": 500,
        "season": "1,2,11,12月",
        "time": "終日",
        "place": "空中",
    },
    {
        "id": 156,
        "name": "ホタル",
        "category": "虫",
        "price": 300,
        "season": "6月",
        "time": "0時~4時,19時~24時",
        "place": "空中（水辺付近）",
    },
    {
        "id": 157,
        "name": "オケラ",
        "category": "虫",
        "price": 500,
        "season": "1,2,3,4,5,11,12月",
        "time": "終日",
        "place": "地上（穴を掘る）",
    },
    {
        "id": 158,
        "name": "アメンボ",
        "category": "虫",
        "price": 130,
        "season": "5,6,7,8,9月",
        "time": "8時~19時",
        "place": "水面",
    },
    {
        "id": 159,
        "name": "ゲンゴロウ",
        "category": "虫",
        "price": 800,
        "season": "5,6,7,8,9月",
        "time": "8時~19時",
        "place": "水面",
    },
    {
        "id": 160,
        "name": "タガメ",
        "category": "虫",
        "price": 2000,
        "season": "4,5,6,7,8,9月",
        "time": "0時~8時,19時~24時",
        "place": "水面",
    },
    {
        "id": 161,
        "name": "カメムシ",
        "category": "虫",
        "price": 120,
        "season": "3,4,5,6,7,8,9,10月",
        "time": "終日",
        "place": "花の上",
    },
    {
        "id": 162,
        "name": "ジンメンカメムシ",
        "category": "虫",
        "price": 1000,
        "season": "3,4,5,6,7,8,9,10月",
        "time": "0時~8時,19時~24時",
        "place": "花の上",
    },
    {
        "id": 163,
        "name": "テントウムシ",
        "category": "虫",
        "price": 200,
        "season": "3,4,5,6,10月",
        "time": "8時~17時",
        "place": "花の上",
    },
    {
        "id": 164,
        "name": "ハンミョウ",
        "category": "虫",
        "price": 1500,
        "season": "2,3,4,5,6,7,8,9,10月",
        "time": "終日",
        "place": "地上",
    },
    {
        "id": 165,
        "name": "タマムシ",
        "category": "虫",
        "price": 2400,
        "season": "4,5,6,7,8月",
        "time": "終日",
        "place": "切り株の上",
    },
    {
        "id": 166,
        "name": "バイオリンムシ",
        "category": "虫",
        "price": 450,
        "season": "5,6,9,10,11月",
        "time": "終日",
        "place": "切り株の上",
    },
    {
        "id": 167,
        "name": "ゴマダラカミキリ",
        "category": "虫",
        "price": 350,
        "season": "通年",
        "time": "終日",
        "place": "切り株の上",
    },
    {
        "id": 168,
        "name": "ルリボシカミキリ",
        "category": "虫",
        "price": 3000,
        "season": "5,6,7,8,9月",
        "time": "終日",
        "place": "切り株の上",
    },
    {
        "id": 169,
        "name": "ホウセキゾウムシ",
        "category": "虫",
        "price": 800,
        "season": "7,8月",
        "time": "終日",
        "place": "ヤシの木",
    },
    {
        "id": 170,
        "name": "フンコロガシ",
        "category": "虫",
        "price": 3000,
        "season": "1,2,12月",
        "time": "終日",
        "place": "地上（雪玉を転がす）",
    },
    {
        "id": 171,
        "name": "オオセンチコガネ",
        "category": "虫",
        "price": 300,
        "season": "7,8,9月",
        "time": "終日",
        "place": "地上",
    },
    {
        "id": 172,
        "name": "プラチナコガネ",
        "category": "虫",
        "price": 10000,
        "season": "7,8月",
        "time": "0時~8時,23時~24時",
        "place": "木/ヤシの木",
    },
    {
        "id": 173,
        "name": "カナブン",
        "category": "虫",
        "price": 200,
        "season": "6,7,8月",
        "time": "終日",
        "place": "木/ヤシの木",
    },
    {
        "id": 174,
        "name": "ゴライアスオオツノハナムグリ",
        "category": "虫",
        "price": 8000,
        "season": "6,7,8,9月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 175,
        "name": "ノコギリクワガタ",
        "category": "虫",
        "price": 2000,
        "season": "7,8月",
        "time": "終日",
        "place": "木/ヤシの木",
    },
    {
        "id": 176,
        "name": "ミヤマクワガタ",
        "category": "虫",
        "price": 1000,
        "season": "7,8月",
        "time": "終日",
        "place": "木/ヤシの木",
    },
    {
        "id": 177,
        "name": "オオクワガタ",
        "category": "虫",
        "price": 10000,
        "season": "7,8月",
        "time": "0時~8時,23時~24時",
        "place": "木/ヤシの木",
    },
    {
        "id": 178,
        "name": "ニジイロクワガタ",
        "category": "虫",
        "price": 6000,
        "season": "6,7,8,9月",
        "time": "0時~8時,19時~24時",
        "place": "木/ヤシの木",
    },
    {
        "id": 179,
        "name": "ホソアカクワガタ",
        "category": "虫",
        "price": 8000,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 180,
        "name": "オウゴンオニクワガタ",
        "category": "虫",
        "price": 12000,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 181,
        "name": "ギラファノコギリクワガタ",
        "category": "虫",
        "price": 12000,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 182,
        "name": "カブトムシ",
        "category": "虫",
        "price": 1350,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "木/ヤシの木",
    },
    {
        "id": 183,
        "name": "コーカサスオオカブト",
        "category": "虫",
        "price": 8000,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 184,
        "name": "ゾウカブト",
        "category": "虫",
        "price": 8000,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 185,
        "name": "ヘラクレスオオカブト",
        "category": "虫",
        "price": 12000,
        "season": "7,8月",
        "time": "0時~8時,17時~24時",
        "place": "ヤシの木",
    },
    {
        "id": 186,
        "name": "ナナフシ",
        "category": "虫",
        "price": 600,
        "season": "7,8,9,10,11月",
        "time": "4時~8時,17時~19時",
        "place": "木/ヤシの木",
    },
    {
        "id": 187,
        "name": "コノハムシ",
        "category": "虫",
        "price": 600,
        "season": "7,8,9月",
        "time": "終日",
        "place": "地上（葉っぱに擬態）",
    },
    {
        "id": 188,
        "name": "ミノムシ",
        "category": "虫",
        "price": 600,
        "season": "通年",
        "time": "終日",
        "place": "木（揺らすと出現）",
    },
    {
        "id": 189,
        "name": "アリ",
        "category": "虫",
        "price": 80,
        "season": "通年",
        "time": "終日",
        "place": "地上（腐ったカブ・アメ・ロリポップ放置）",
    },
    {
        "id": 190,
        "name": "ヤドカリ",
        "category": "虫",
        "price": 1000,
        "season": "通年",
        "time": "0時~8時,19時~24時",
        "place": "地上（貝がらに擬態）",
    },
    {
        "id": 191,
        "name": "フナムシ",
        "category": "虫",
        "price": 200,
        "season": "通年",
        "time": "終日",
        "place": "岩礁（海岸の岩）",
    },
    {
        "id": 192,
        "name": "ハエ",
        "category": "虫",
        "price": 60,
        "season": "通年",
        "time": "終日",
        "place": "空中（ゴミ放置で出現）",
    },
    {
        "id": 193,
        "name": "カ",
        "category": "虫",
        "price": 130,
        "season": "6,7,8,9月",
        "time": "0時~4時,17時~24時",
        "place": "空中",
    },
    {
        "id": 194,
        "name": "ノミ",
        "category": "虫",
        "price": 70,
        "season": "4,5,6,7,8,9,10,11月",
        "time": "終日",
        "place": "住民の体",
    },
    {
        "id": 195,
        "name": "カタツムリ",
        "category": "虫",
        "price": 250,
        "season": "通年",
        "time": "終日",
        "place": "石/低木の上（雨の日のみ）",
    },
    {
        "id": 196,
        "name": "ダンゴムシ",
        "category": "虫",
        "price": 250,
        "season": "1,2,3,4,5,6,9,10,11,12月",
        "time": "0時~16時,23時~24時",
        "place": "地上（石を叩く）",
    },
    {
        "id": 197,
        "name": "ムカデ",
        "category": "虫",
        "price": 300,
        "season": "1,2,3,4,5,6,9,10,11,12月",
        "time": "16時~23時",
        "place": "地上（石を叩く）",
    },
    {
        "id": 198,
        "name": "クモ",
        "category": "虫",
        "price": 600,
        "season": "通年",
        "time": "0時~8時,19時~24時",
        "place": "木（揺すると出現）",
    },
    {
        "id": 199,
        "name": "タランチュラ",
        "category": "虫",
        "price": 8000,
        "season": "1,2,3,4,11,12月",
        "time": "0時~4時,19時~24時",
        "place": "地上",
    },
    {
        "id": 200,
        "name": "サソリ",
        "category": "虫",
        "price": 8000,
        "season": "5,6,7,8,9,10月",
        "time": "0時~4時,19時~24時",
        "place": "地上",
    },
]
